function Adam(n=".") {return "Adam"+n}
function has(n=".") {return " has "+n}
function a(n=".") { return "a "+n}
function dog(n=".") { return "dog"+n}
function The(n=".") {return "The "+n}
function name(n=".") {return "name "+n}
function of(n=".") {return "of "+n}
function the(n=".") {return "the "+n}
function is(n=".") {return " is "+n}
function also(n=".") {return "also "+n}